CREATE DATABASE SAMPLE_DB;

USE SAMPLE_DB;

CREATE TABLE STUDENT
(
	studentRoll INTEGER PRIMARY KEY,
	studentName VARCHAR(25) NOT NULL,
	phoneNo VARCHAR(20) NOT NULL,
	studentClass VARCHAR(10)
);