USE SAMPLE_DB;

CREATE TABLE ddl_logs(ID INT IDENTITY PRIMARY KEY,EVENT_DATA XML,PERFORMED_BY SYSNAME,EVENT_TYPE VARCHAR(30));

GO
CREATE OR ALTER TRIGGER ddl_Trigger_Log
ON DATABASE
FOR CREATE_TABLE,RENAME,DROP_TABLE
AS
BEGIN
	INSERT INTO ddl_logs(EVENT_DATA,PERFORMED_BY,EVENT_TYPE)
	VALUES (EVENTDATA(),USER,EVENTDATA().value('(/EVENT_INSTANCE/EventType)[1]','VARCHAR(MAX)'));
END

GO
SP_RENAME 'Pratice','Practice';
CREATE TABLE TEST(ID INT,NAME VARCHAR(20));

SELECT * FROM ddl_logs;
DROP TABLE TEST;
