USE SAMPLE_DB;

GO
CREATE TRIGGER tr_message
ON EMPLOYE
AFTER INSERT
AS
BEGIN 
	PRINT 'New column is added'
END

INSERT INTO EMPLOYE VALUES(10,'ARIJIT ROY','JSD',30000,22,9374567234);

SELECT * FROM EMPLOYE;