USE SAMPLE_DB;

SELECT * FROM EMPLOYE;
SELECT * FROM EMP_ADDRESS;

SELECT employeName,dept,SALARY,address FROM EMPLOYE FULL OUTER JOIN EMP_ADDRESS ON EMPLOYE.employeId=EMP_ADDRESS.employeId;

DELETE FROM EMP_ADDRESS WHERE employeId=1;
DELETE FROM EMP_ADDRESS WHERE employeId=6;
DELETE FROM EMPLOYE WHERE employeId=5;
