USE SAMPLE_DB;

BEGIN
DECLARE @SALARY INT;
SELECT @SALARY=AVG(SALARY) FROM EMPLOYE;
SELECT @SALARY AS SALARY;
	IF(@SALARY>10000)
	BEGIN
		PRINT 'SALARY IS GREATER THAN 10000';
	END
	ELSE
	BEGIN
		PRINT 'SALARY IS LESSER THAN 10000';
	END
END