USE SAMPLE_DB;

GO
CREATE FUNCTION getEmployeeDetailsByDept(@dept AS VARCHAR(30))
RETURNS @table TABLE
(ID INT,NAME VARCHAR(20),DEPT VARCHAR(20),SALARY DECIMAL,AGE INT,NUMBER INT)
AS 
BEGIN
	INSERT INTO @table
	SELECT* FROM EMPLOYE WHERE DEPT=@dept;
	RETURN
END
GO

SELECT * FROM getEmployeeDetailsByDept('SD');