USE SAMPLE_DB;

SELECT*FROM EMPLOYE;

GO
CREATE PROCEDURE proc_Employe_Dept(@DEPT VARCHAR(30))
AS
BEGIN
	SELECT * FROM EMPLOYE WHERE DEPT=@DEPT;
END
GO

EXECUTE proc_Employe_Dept @DEPT= 'SDE';