USE SAMPLE_DB;

SELECT * FROM EMPLOYE;

SELECT LEN('TANMOY');

SELECT employeName,LEN(employeName) FROM EMPLOYE;

SELECT LTRIM('    TANMOY');

SELECT RTRIM('TANMOY    ');

SELECT SUBSTRING(employeName,2,5) FROM EMPLOYE;

SELECT REPLACE(studentClass,'4','3') FROM STUDENT;

SELECT REPLICATE('TANMOY ',4);