BEGIN TRY
	SELECT 100/5 AS 'DIVISION';
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE() AS 'ERROR';
END CATCH

BEGIN TRY
	SELECT 100/0 AS 'DIVISION';
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE() AS 'ERROR';
END CATCH

BEGIN TRY
	SELECT 100/0 AS 'DIVISION';
END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE() AS 'ERROR',ERROR_LINE() AS 'ERROR LINE',ERROR_NUMBER() AS 'ERROR NUMBER',ERROR_STATE() AS 'ERROR STATE';
END CATCH