USE SAMPLE_DB;

BEGIN
	WHILE(SELECT MIN(SALARY) FROM EMPLOYE)<30000
	BEGIN
		UPDATE EMPLOYE SET SALARY+=10000;
		IF(SELECT MIN(SALARY) FROM EMPLOYE)>30000
		BEGIN
			PRINT 'ALL SALARY DETAILS ARE UPDATED';
			SELECT * FROM EMPLOYE;
			BREAK;
		END
	END
END